blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls', namespace='main')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, password_recovery

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path("email-confirm/<str:token>/", email_verification, name='email-confirm'),
    path("password_recovery/", password_recovery, name='password_recovery'),


]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    token = models.CharField(max_length=100, verbose_name="токен", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from main.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets
import string
import random

from django.conf.global_settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        # print(url)
        send_mail(
            subject='Подтверждение почты',
            message=f'Перейдите по ссылке для подтверждения почты {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        # print(f'Отправлено {EMAIL_HOST_USER} to {user.email}')
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def password_recovery(request):
    context = {
        'success_message': 'Пароль успешно сброшен. Новый пароль был отправлен на адрес электронной почты.',
    }
    if request.method == 'POST':
        email = request.POST.get('email')

        print(f'Получен адрес {email}')

        user = get_object_or_404(User, email=email)
        characters = string.ascii_letters + string.digits
        characters_list = list(characters)
        random.shuffle(characters_list)
        password = ''.join(characters_list[:10])
        print(f'Пользователь {user}')

        print(f'Пароль {password}')

        message = f"Сгенерирован пароль: {password}."

        print(f'Пароль {message}')

        send_mail(
            subject='Восстановление пароля',
            message=message,
            from_email=EMAIL_HOST_USER,
            recipient_list=[email]
        )

        user.set_password(password)
        user.save()
        return render(request, 'users/reset_password.html', context)

    return render(request, 'users/password_recovery.html')

users/templates/users/login.html
{% extends 'main/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Вход</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                        {% csrf_token %}
                        {{form.as_p}}


                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Войти
                    </button>
                     <br><br>
                     <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'users:password_recovery'%}">Отправить пароль на почту</a>
                    <br><br>


                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/password_recovery.html
{% extends 'main/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Восстановление пароля</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                        {% csrf_token %}
                        <label for="email">Почта для восстановления</label>
                        <input type="text" name="email" class="form-control" id="email" placeholder="введите ваш email"
                               required>


                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Отправить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Регистрация</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="mb-3">

                        {% csrf_token %}
                        {{form.as_p}}


                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Зарегистрироваться
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html'%}
{% block content %}


<div class="row text-start">

    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Профиль</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                    <div class="mb-3">

                        {% csrf_token %}
                        {{form.as_p}}


                    </div>


                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Сохранить
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}